import XCTest
@testable import SoloLedgerCore

/// `toLocaleString()` — replayed against a corpus recorded from the real V8 under the
/// same pinned runtime the goldens use.
///
/// This is the only ICU-dependent expression in `electron/reports/*` (`us.js:120`),
/// and the only one a device-locale `NumberFormatter` would silently get wrong on a
/// non-US machine. The corpus is generated by
/// `Tests/Fixtures/make-tolocalestring-corpus.mjs` under `LC_ALL=C LANG=C TZ=UTC` and
/// the Electron binary package.json locks; `--verify` is wired into `check:all`.
///
/// **Where Swift and the corpus disagree, the corpus is right.**
final class ReportToLocaleStringTests: XCTestCase {

    private struct Corpus: Decodable {
        struct Vector: Decodable { let bits: String; let repr: String; let formatted: String }
        let resolvedIntlLocale: String
        let expression: String
        let vectors: [Vector]
    }

    private func corpus() throws -> Corpus {
        let dir = try XCTUnwrap(Bundle.module.url(forResource: "reportmath", withExtension: nil),
                                "toLocaleString corpus missing from the test bundle")
        let data = try Data(contentsOf: dir.appendingPathComponent("js-tolocalestring.json"))
        return try JSONDecoder().decode(Corpus.self, from: data)
    }

    private func double(fromBits hex: String) -> Double {
        let raw = UInt64(hex.dropFirst(2), radix: 16) ?? 0
        return Double(bitPattern: raw)
    }

    func testEveryRecordedVectorMatches() throws {
        let c = try corpus()
        XCTAssertEqual(c.resolvedIntlLocale, "en-US",
                       "the corpus must be recorded under the locale the goldens pin")
        XCTAssertEqual(c.expression, "value.toLocaleString()")
        XCTAssertFalse(c.vectors.isEmpty)
        for v in c.vectors {
            let d = double(fromBits: v.bits)
            XCTAssertEqual(ReportMath.toLocaleString(d), v.formatted,
                           "\(v.repr) (bits \(v.bits))")
        }
    }

    /// The four properties that make this shim non-obvious, named so a reader does not
    /// have to reverse-engineer them from 46 vectors.
    ///
    /// **These are documentation, not an oracle.** Every value below also appears in
    /// the V8-recorded corpus above, so nothing here is a hand-written expectation
    /// standing on its own — if one of them disagreed with V8, the corpus test would
    /// have failed first.
    func testTheFourQuirksThatMatter() {
        // 1. Trailing zeros are dropped — Appendix A3, mirrored not repaired.
        XCTAssertEqual(ReportMath.toLocaleString(3647.60), "3,647.6")
        // 2. Three fraction digits, rounded half away from zero (NOT truncated).
        XCTAssertEqual(ReportMath.toLocaleString(1.2345), "1.235")
        XCTAssertEqual(ReportMath.toLocaleString(0.0005), "0.001")
        // 3. Negative zero keeps its sign here, unlike JS String(-0).
        XCTAssertEqual(ReportMath.toLocaleString(-0.0), "-0")
        // 4. No exponential notation anywhere in the double range.
        XCTAssertEqual(ReportMath.toLocaleString(1e21), "1,000,000,000,000,000,000,000")
    }
}
