import XCTest
@testable import SoloLedgerCore

/// Differential test of `ReportMath` against V8.
///
/// The corpus is produced by `Tests/Fixtures/make-reportmath-corpus.mjs`, which
/// executes each operation in a real JavaScript engine using the same expression
/// the report engines are written with. Swift cannot run JavaScript, so this file
/// does not verify the shim so much as REPLAY the recorded truth against it.
///
/// The direction matters and is the whole discipline of the mirroring phase: when
/// this suite goes red, the corpus is right and `ReportMath.swift` is wrong. That
/// holds even against the specification's own prose — ECMA-262's note claiming
/// `Math.round(x) === Math.floor(x + 0.5)` is inaccurate for the
/// `0.49999999999999994` family, and the engine, not the note, is what the goldens
/// were generated by.
final class ReportMathTests: XCTestCase {

    // MARK: - Corpus loading

    private struct Corpus {
        let header: [String: Any]
        let cases: [[Any]]
        let numberCases: [[Any]]
    }

    /// Loads the corpus, or FAILS.
    ///
    /// Deliberately not `XCTSkip`. A skip is the wrong failure mode for the only
    /// thing in the repository that checks Swift against V8: dropping one line
    /// from `Package.swift`'s `resources:` would delete the entire differential
    /// replay and `swift test` would still exit 0, with `check:reportmath` none
    /// the wiser because it re-executes the corpus in node and never looks at
    /// Swift. A suite that reports success while checking nothing is worse than a
    /// red one, so a missing resource is an error.
    private func loadCorpus() throws -> Corpus {
        let dir = try XCTUnwrap(Bundle.module.url(forResource: "reportmath", withExtension: nil),
                                "reportmath corpus is not in the test bundle — check the " +
                                "resources: list in Package.swift. This must FAIL, never skip: " +
                                "without the corpus nothing here is verified against V8.")
        let data = try Data(contentsOf: dir.appendingPathComponent("js-numeric-semantics.json"))
        let root = try XCTUnwrap(try JSONSerialization.jsonObject(with: data) as? [String: Any])
        return Corpus(
            header: try XCTUnwrap(root["header"] as? [String: Any]),
            cases: try XCTUnwrap(root["cases"] as? [[Any]]),
            numberCases: try XCTUnwrap(root["numberCases"] as? [[Any]])
        )
    }

    /// `Object.is` semantics, with one deliberate relaxation: two NaNs compare
    /// equal regardless of payload. NaN payloads are not architecturally
    /// guaranteed and the generator canonicalizes them, so requiring bit equality
    /// there would test the hardware rather than the shim. Everything else —
    /// crucially `-0` vs `+0` — is compared BIT-for-bit.
    private func identical(_ a: Double, _ b: Double) -> Bool {
        if a.isNaN && b.isNaN { return true }
        return a.bitPattern == b.bitPattern
    }

    private func double(fromBits hex: String) throws -> Double {
        Double(bitPattern: try XCTUnwrap(UInt64(hex, radix: 16), "bad bit pattern \(hex)"))
    }

    /// A corpus argument: a hex bit pattern, or JSON `null` meaning JS
    /// `null`/`undefined` and SQL `NULL` alike — all three reach Swift as `nil`.
    private func argument(_ raw: Any) throws -> Double? {
        if raw is NSNull { return nil }
        return try double(fromBits: try XCTUnwrap(raw as? String))
    }

    // MARK: - The dispatch table
    //
    // One entry per public operation. `testEveryOperationIsExercised` asserts this
    // table and the corpus agree on the op list in BOTH directions, so a shim
    // cannot ship without cases and a case cannot sit unread.

    private enum Produced {
        case number(Double)
        case numberOrNil(Double?)
        case boolean(Bool)
    }

    private func apply(_ op: String, _ args: [Double?]) throws -> Produced {
        switch op {
        case "round":        return .number(ReportMath.round(try XCTUnwrap(args[0])))
        case "round2":       return .number(ReportMath.round2(try XCTUnwrap(args[0])))
        case "round2OrZero": return .number(ReportMath.round2OrZero(args[0]))
        case "percent2":     return .number(ReportMath.percent2(try XCTUnwrap(args[0])))
        case "isTruthy":     return .boolean(ReportMath.isTruthy(args[0]))
        case "orZero":       return .number(ReportMath.orZero(args[0]))
        case "or":           return .numberOrNil(ReportMath.or(args[0], args[1]))
        case "netAmount":    return .number(ReportMath.netAmount(args[0], args[1]))
        case "max":          return .number(ReportMath.max(try XCTUnwrap(args[0]),
                                                           try XCTUnwrap(args[1])))
        case "min":          return .number(ReportMath.min(try XCTUnwrap(args[0]),
                                                           try XCTUnwrap(args[1])))
        default:
            XCTFail("corpus contains operation '\(op)' that this test cannot dispatch")
            return .number(.nan)
        }
    }

    private var dispatchableOps: Set<String> {
        ["round", "round2", "round2OrZero", "percent2",
         "isTruthy", "orZero", "or", "netAmount", "max", "min"]
    }

    // MARK: - The differential replay

    func testSwiftReproducesEveryRecordedJavaScriptResult() throws {
        let corpus = try loadCorpus()
        var matched = 0
        var failures: [String] = []

        for row in corpus.cases {
            let op = try XCTUnwrap(row[0] as? String)
            // `try`, not `try?`: an unreadable bit pattern must fail the test, not
            // decode to nil — nil is a MEANINGFUL input here (it is JS null, which
            // every `||` case depends on), so swallowing a decode error would turn
            // corpus corruption into a silently passing falsy case.
            let args = try XCTUnwrap(row[1] as? [Any]).map { try argument($0) }
            let readable = try XCTUnwrap(row[4] as? String)

            let produced = try apply(op, args)
            var ok = false
            switch produced {
            case .boolean(let b):
                ok = (b == (row[2] as? Bool))
            case .numberOrNil(let v):
                if row[2] is NSNull {
                    ok = (v == nil)
                } else if let v {
                    ok = identical(v, try double(fromBits: try XCTUnwrap(row[2] as? String)))
                }
            case .number(let v):
                ok = identical(v, try double(fromBits: try XCTUnwrap(row[2] as? String)))
            }

            if ok {
                matched += 1
            } else if failures.count < 20 {
                let got: String
                switch produced {
                case .boolean(let b): got = String(b)
                case .numberOrNil(let v): got = v.map(describe) ?? "nil"
                case .number(let v): got = describe(v)
                }
                failures.append("  JS: \(readable)  |  Swift: \(got)")
            }
        }

        XCTAssertEqual(matched, corpus.cases.count,
                       "\(corpus.cases.count - matched) of \(corpus.cases.count) cases disagree " +
                       "with V8. The corpus is the ground truth — fix ReportMath, not the corpus." +
                       (failures.isEmpty ? "" : "\n" + failures.joined(separator: "\n")))
        // A corpus that failed to load would leave both sides at 0 and the equality
        // above would hold vacuously.
        XCTAssertGreaterThan(corpus.cases.count, 1000, "the corpus did not load")
    }

    func testSwiftReproducesEveryRecordedNumberCoercion() throws {
        let corpus = try loadCorpus()
        for row in corpus.numberCases {
            let encoded = try XCTUnwrap(row[0] as? [String: Any])
            let expected = try double(fromBits: try XCTUnwrap(row[1] as? String))
            let readable = try XCTUnwrap(row[2] as? String)
            let value = try decodeJSValue(encoded)
            let actual = ReportMath.number(value)
            XCTAssertTrue(identical(actual, expected),
                          "Number(\(value)) — JS: \(readable), Swift: \(describe(actual))")
        }
    }

    private func decodeJSValue(_ e: [String: Any]) throws -> ReportMath.JSValue {
        switch try XCTUnwrap(e["t"] as? String) {
        case "undefined": return .undefined
        case "null":      return .null
        case "obj":       return .object
        case "bool":      return .boolean(try XCTUnwrap(e["v"] as? Bool))
        case "str":       return .string(try XCTUnwrap(e["v"] as? String))
        // Numbers ride as bits for the same reason everything else does:
        // JSON.stringify(-0) is "0", so a plain number would lose the sign.
        case "num":       return .number(try double(fromBits: try XCTUnwrap(e["bits"] as? String)))
        case "arr":
            return .array(try XCTUnwrap(e["v"] as? [[String: Any]]).map { try decodeJSValue($0) })
        default:
            XCTFail("unknown encoded tag in corpus: \(e)"); return .undefined
        }
    }

    private func describe(_ d: Double) -> String {
        if d.isNaN { return "NaN" }
        if d == 0 { return d.sign == .minus ? "-0" : "0" }
        return String(d)
    }

    // MARK: - The corpus is complete and discriminating
    //
    // Same reasoning as ReportGoldenFixtureTests: a corpus that cannot tell two
    // implementations apart turns the replay above into a test that passes for the
    // wrong reason.

    func testEveryOperationIsExercised() throws {
        let corpus = try loadCorpus()
        let declared = Set(try XCTUnwrap(corpus.header["ops"] as? [String: Any]).keys)
        let exercised = Set(corpus.cases.compactMap { $0[0] as? String })

        XCTAssertEqual(declared, dispatchableOps,
                       "the generator's op list and this test's dispatch table drifted apart")
        XCTAssertEqual(exercised, dispatchableOps,
                       "an operation is declared but has no cases, or vice versa")

        // Per-op floor. A single case per op would satisfy the set equality above
        // while testing essentially nothing.
        //
        // Counted from `corpus.cases` itself, NOT from the header's self-reported
        // `counts` — a floor that trusts the artefact's own summary of itself is
        // only as good as whatever keeps the summary honest, and that is a second
        // gate (`check:reportmath`) in a different language. Count what is there.
        var byOp: [String: Int] = [:]
        for row in corpus.cases { byOp[(row[0] as? String) ?? "", default: 0] += 1 }
        for op in dispatchableOps {
            XCTAssertGreaterThan(byOp[op] ?? 0, 100, "\(op) is barely covered")
        }
        // `Number()` is the shim's largest function and its own half of the corpus,
        // reached by a different code path entirely — without its own floor it could
        // shrink to a single case and every assertion here would still hold.
        XCTAssertGreaterThan(corpus.numberCases.count, 150,
                             "the Number() half of the corpus shrank")
        // Both halves of the corpus must be present: the named adversarial cases
        // AND the fixed-seed random draw (plan constraint 4 — random never reaches
        // the spec edges, and the named set never covers a whole region).
        var byTag: [String: Int] = [:]
        for row in corpus.cases { byTag[(row[3] as? String) ?? "", default: 0] += 1 }
        for tag in ["boundary", "currency", "extreme", "preimage",
                    "truthiness", "clamp", "callsite", "random"] {
            XCTAssertGreaterThan(byTag[tag] ?? 0, 0, "the '\(tag)' case family vanished")
        }
    }

    /// The inputs that motivated each shim must actually BE in the corpus. Without
    /// this, a regenerated corpus that quietly dropped the adversarial list would
    /// still pass every assertion above.
    func testTheMotivatingInputsArePresent() throws {
        let corpus = try loadCorpus()
        let required: [(op: String, bits: String, why: String)] = [
            ("round", "3FDFFFFFFFFFFFFF", "0.49999999999999994 — where floor(x+0.5) breaks"),
            ("round", "BFE0000000000000", "-0.5 — where .rounded() breaks the sign"),
            ("round", "C029000000000000", "-12.5 — the r(-0.125) tie the plan names"),
            ("round", "8000000000000000", "-0 — must survive as -0"),
            ("round2", "3FF0147AE147AE14", "1.005 — the currency-precision quirk"),
            // The spec divergence reached through a MONEY value rather than a
            // hand-picked constant: 0.004999999999999999 * 100 is exactly
            // 0.49999999999999994. Without this the divergence looks academic.
            ("round2", "3F747AE147AE147A", "0.004999999999999999 — the scaled preimage"),
            ("max", "7FF8000000000000", "NaN — Swift.max swallows it"),
            ("min", "7FF8000000000000", "NaN — Swift.min is argument-order dependent"),
        ]
        for (op, bits, why) in required {
            let present = corpus.cases.contains { row in
                (row[0] as? String) == op &&
                ((row[1] as? [Any])?.contains { ($0 as? String) == bits } ?? false)
            }
            XCTAssertTrue(present, "corpus lost the \(op) case for \(why)")
        }
    }

    // MARK: - Each shim earns its existence
    //
    // These assert that the SWIFT-IDIOMATIC spelling is measurably wrong on the
    // corpus. Without them a future "simplification" back to `.rounded()` / `??` /
    // `Swift.max` would be a silent behaviour change, since a reviewer has no way
    // to see from the diff that the stdlib version answers differently.

    func testStdlibRoundingWouldDisagreeWithV8() throws {
        let corpus = try loadCorpus()
        var awayFromZeroWrong = 0, floorPlusHalfWrong = 0
        for row in corpus.cases where (row[0] as? String) == "round" {
            guard let x = try argument(try XCTUnwrap(row[1] as? [Any])[0]) else { continue }
            let expected = try double(fromBits: try XCTUnwrap(row[2] as? String))
            if !identical(x.rounded(), expected) { awayFromZeroWrong += 1 }
            if !identical((x + 0.5).rounded(.down), expected) { floorPlusHalfWrong += 1 }
        }
        XCTAssertGreaterThan(awayFromZeroWrong, 0,
                             "x.rounded() rounds ties away from zero; JS rounds them toward +∞")
        XCTAssertGreaterThan(floorPlusHalfWrong, 0,
                             "floor(x+0.5) is what ECMA-262's NOTE claims and it is not what V8 does")
    }

    func testNilCoalescingWouldDisagreeWithV8() throws {
        let corpus = try loadCorpus()
        var wrong = 0
        for row in corpus.cases where (row[0] as? String) == "netAmount" {
            let raw = try XCTUnwrap(row[1] as? [Any])
            let a = try argument(raw[0]), b = try argument(raw[1])
            let expected = try double(fromBits: try XCTUnwrap(row[2] as? String))
            if !identical(a ?? b ?? 0, expected) { wrong += 1 }   // the `??` spelling
        }
        XCTAssertGreaterThan(wrong, 0,
                             "`??` keeps 0, -0 and NaN; JS `||` treats all three as falsy")
    }

    func testStdlibClampsWouldDisagreeWithV8() throws {
        let corpus = try loadCorpus()
        var maxWrong = 0, minWrong = 0
        for row in corpus.cases {
            guard let op = row[0] as? String, op == "max" || op == "min" else { continue }
            let raw = try XCTUnwrap(row[1] as? [Any])
            guard let a = try argument(raw[0]), let b = try argument(raw[1]) else { continue }
            let expected = try double(fromBits: try XCTUnwrap(row[2] as? String))
            if op == "max", !identical(Swift.max(a, b), expected) { maxWrong += 1 }
            if op == "min", !identical(Swift.min(a, b), expected) { minWrong += 1 }
        }
        XCTAssertGreaterThan(maxWrong, 0, "Swift.max swallows NaN and mis-orders signed zero")
        XCTAssertGreaterThan(minWrong, 0, "Swift.min swallows NaN and mis-orders signed zero")
    }

    func testDoubleStringInitWouldDisagreeWithV8() throws {
        let corpus = try loadCorpus()
        var wrong: [String] = []
        for row in corpus.numberCases {
            let e = try XCTUnwrap(row[0] as? [String: Any])
            guard (e["t"] as? String) == "str", let s = e["v"] as? String else { continue }
            let expected = try double(fromBits: try XCTUnwrap(row[1] as? String))
            if !identical(Double(s) ?? .nan, expected) { wrong.append(s) }
        }
        XCTAssertFalse(wrong.isEmpty,
                       "Double(String) is not the JS StringNumericLiteral grammar")
    }

    // MARK: - Targeted cases, one per documented quirk
    //
    // The replay above already covers all of these. They are spelled out anyway so
    // a failure names the QUIRK rather than a bit pattern, and so the engine line
    // each one protects is visible at the failure site.

    /// `electron/reports/cn.js:43` — `r(-0.125)` is `Math.round(-12.5)/100`, and
    /// JS breaks the tie toward +∞. Named explicitly in the mirror plan §8.1.
    func testNegativeHalfCentTiesRoundTowardPositiveInfinity() {
        XCTAssertEqual(ReportMath.round2(-0.125), -0.12)
        XCTAssertEqual(ReportMath.round2(-0.135), -0.13)
        XCTAssertEqual(ReportMath.round2(0.125), 0.13)
        XCTAssertEqual(ReportMath.round(-12.5), -12)
        XCTAssertEqual(ReportMath.round(-2.5), -2)
    }

    /// The ECMA-262 NOTE on `Math.round` claims `floor(x + 0.5)` equivalence. For
    /// this input the note is wrong: `x + 0.5` rounds up to exactly `1.0`.
    func testTheSpecNoteFamilyFollowsTheEngineNotTheFormula() {
        XCTAssertEqual(ReportMath.round(0.49999999999999994), 0)
        XCTAssertEqual((0.49999999999999994 + 0.5).rounded(.down), 1,
                       "if this stops being 1, the divergence this test guards has gone away")
    }

    /// Signed zero survives the engines' trailing `/ 100`
    /// (`Math.round(-0.001 * 100) / 100` is `-0` in node), so the mirror must not
    /// normalize it away.
    func testNegativeZeroIsPreserved() {
        XCTAssertEqual(ReportMath.round(-0.4).sign, .minus)
        XCTAssertEqual(ReportMath.round(-0.5).sign, .minus)
        XCTAssertEqual(ReportMath.round2(-0.001).sign, .minus)
        XCTAssertEqual(ReportMath.round(-0.0).sign, .minus)
        XCTAssertEqual(ReportMath.round(0.4).sign, .plus)
    }

    /// `1.005 * 100` is `100.49999999999999` in binary64, so the "obvious" answer
    /// `1.01` is not what the engines produce. Reproducing this is the reason
    /// `ReportMath` is `Double` and never `Decimal`.
    func testCurrencyPrecisionLossIsReproducedNotRepaired() {
        XCTAssertEqual(ReportMath.round2(1.005), 1.0, "NOT 1.01 — binary64 lands just under the half")
        XCTAssertEqual(ReportMath.round2(1.015), 1.01, "NOT 1.02")
        XCTAssertEqual(ReportMath.round2(0.615), 0.62, "this one DOES land on the half")
        XCTAssertEqual(1.005 * 100, 100.49999999999999,
                       "if this changes, Swift stopped being IEEE-754 binary64")
    }

    /// `_expenseSplit.js:24` and every engine's `amount_net || amount || 0`.
    /// A row whose net amount is exactly 0 falls back to the TAX-INCLUSIVE amount.
    func testZeroNetAmountFallsBackToTheTaxInclusiveAmount() {
        XCTAssertEqual(ReportMath.netAmount(0, 113), 113)
        XCTAssertEqual(ReportMath.netAmount(-0.0, 113), 113)
        XCTAssertEqual(ReportMath.netAmount(.nan, 113), 113)
        XCTAssertEqual(ReportMath.netAmount(nil, 113), 113)
        XCTAssertEqual(ReportMath.netAmount(100, 113), 100)
        XCTAssertEqual(ReportMath.netAmount(nil, nil), 0)
        XCTAssertEqual(0 as Double? ?? 113, 0, "the `??` spelling keeps the 0 — that is the bug")
    }

    /// `cn.js:39` — `Math.max(0, profitBeforeTax)` with an unparseable surcharge
    /// rate. This is what makes `malformed-CN-2025.json` record `incomeTax: null`;
    /// `Swift.max` would answer 0 and the mirror would print a plausible tax.
    func testMaxPropagatesNaNSoTheChinaNullChainSurvives() {
        XCTAssertTrue(ReportMath.max(0, .nan).isNaN)
        XCTAssertTrue(ReportMath.max(.nan, 0).isNaN)
        XCTAssertTrue(ReportMath.min(.nan, 5).isNaN)
        XCTAssertTrue(ReportMath.min(5, .nan).isNaN)
        XCTAssertEqual(Swift.max(0, Double.nan), 0, "the stdlib answer this shim exists to avoid")
        // Signed zero is ORDERED in JS: +0 > -0.
        XCTAssertEqual(ReportMath.max(0, -0.0).sign, .plus)
        XCTAssertEqual(ReportMath.max(-0.0, 0).sign, .plus)
        XCTAssertEqual(ReportMath.min(0, -0.0).sign, .minus)
    }

    /// `index.js:74-78` — the ORIGIN of the engines' NaN path. A settings row
    /// holding `"25%"` coerces to NaN here; a MISSING row never reaches this
    /// function at all because `readSetting` substitutes the fallback first. Plan
    /// §6.2 turns on those being two different things.
    func testNumberCoercionIsWhereTheMalformedRateBecomesNaN() {
        XCTAssertTrue(ReportMath.number(.string("25%")).isNaN)
        XCTAssertTrue(ReportMath.number(.string("12%")).isNaN)
        XCTAssertEqual(ReportMath.number(.string("13")), 13)
        XCTAssertEqual(ReportMath.number(.string(" 12 ")), 12, "JS trims; Double(String) does not")
        XCTAssertEqual(ReportMath.number(.string("")), 0, "the empty string is +0, not NaN")
        XCTAssertEqual(ReportMath.number(.string("   ")), 0)
        XCTAssertEqual(ReportMath.number(.null), 0, "Number(null) is 0 …")
        XCTAssertTrue(ReportMath.number(.undefined).isNaN, "… but Number(undefined) is NaN")
        XCTAssertEqual(ReportMath.number(.string("0b101")), 5, "Double(String) rejects this")
        XCTAssertEqual(ReportMath.number(.string("0o17")), 15)
        XCTAssertTrue(ReportMath.number(.string("0x1p4")).isNaN,
                      "Swift takes hex FLOATS; JS does not")
        XCTAssertEqual(Double("0x1p4"), 16, "the stdlib answer this shim exists to avoid")
        XCTAssertTrue(ReportMath.number(.string("1_000")).isNaN, "separators are source-only")
        XCTAssertEqual(ReportMath.number(.string("017")), 17, "no legacy octal in Number()")
    }

    /// `ReportMath` keeps a HAND-WRITTEN copy of ECMA-262's `StrWhiteSpace`, and a
    /// hand-written set is exactly the kind of thing that goes quietly wrong. Every
    /// one of the 25 members is asserted individually here, in both roles
    /// (whitespace-only trims to `+0`; a prefix/suffix trims away), because a
    /// corpus that samples the set cannot distinguish a complete set from one
    /// missing an entry — an adversarial review deleted U+2001 from the shim and
    /// the whole suite stayed green.
    ///
    /// The negative half matters just as much: `CharacterSet.whitespacesAndNewlines`
    /// would be the obvious Foundation shortcut, its membership is an ICU decision
    /// that can move between OS releases, and it does NOT agree with this set.
    func testTheWhiteSpaceSetMatchesEcma262MemberForMember() {
        let members: [Unicode.Scalar] = [
            "\u{0009}", "\u{000A}", "\u{000B}", "\u{000C}", "\u{000D}", "\u{0020}",
            "\u{00A0}", "\u{1680}", "\u{2000}", "\u{2001}", "\u{2002}", "\u{2003}",
            "\u{2004}", "\u{2005}", "\u{2006}", "\u{2007}", "\u{2008}", "\u{2009}",
            "\u{200A}", "\u{2028}", "\u{2029}", "\u{202F}", "\u{205F}", "\u{3000}",
            "\u{FEFF}",
        ]
        XCTAssertEqual(members.count, 25, "StrWhiteSpace has 25 members")
        for w in members {
            let s = String(w)
            XCTAssertEqual(ReportMath.number(.string(s)), 0,
                           "U+\(String(w.value, radix: 16, uppercase: true)) alone must be +0")
            XCTAssertEqual(ReportMath.number(.string(s + "12")), 12,
                           "U+\(String(w.value, radix: 16, uppercase: true)) must trim as a prefix")
            XCTAssertEqual(ReportMath.number(.string("12" + s)), 12,
                           "U+\(String(w.value, radix: 16, uppercase: true)) must trim as a suffix")
        }
        // Scalars that LOOK blank and are NOT members. U+0085 (NEL) is the sharp
        // one: Foundation counts it as a newline, ECMA-262 does not.
        for other: Unicode.Scalar in ["\u{0085}", "\u{200B}", "\u{00AD}", "\u{180E}",
                                      "\u{2060}", "\u{00B7}"] {
            XCTAssertTrue(ReportMath.number(.string(String(other))).isNaN,
                          "U+\(String(other.value, radix: 16, uppercase: true)) is not StrWhiteSpace")
            XCTAssertTrue(ReportMath.number(.string(String(other) + "12")).isNaN,
                          "U+\(String(other.value, radix: 16, uppercase: true)) must not be trimmed")
        }
    }

    /// The shortest string the radix path accepts. `"0x1"` is three characters, so
    /// the length gate that decides whether a string is a radix literal at all sits
    /// exactly on it — and an off-by-one there would make every single-digit
    /// literal fall through to the decimal parser and answer NaN.
    func testSingleDigitRadixLiteralsAreAccepted() {
        XCTAssertEqual(ReportMath.number(.string("0x1")), 1)
        XCTAssertEqual(ReportMath.number(.string("0xF")), 15)
        XCTAssertEqual(ReportMath.number(.string("0b1")), 1)
        XCTAssertEqual(ReportMath.number(.string("0o7")), 7)
        XCTAssertEqual(ReportMath.number(.string("0x0")), 0)
        // …and the two-character prefixes with NO digit are still NaN.
        for empty in ["0x", "0X", "0b", "0o"] {
            XCTAssertTrue(ReportMath.number(.string(empty)).isNaN, "\(empty) has no digits")
        }
    }

    /// JS's numeric grammar is ASCII-only. Swift's character properties are not:
    /// `hexDigitValue` reads the FULLWIDTH forms (U+FF10 is 0, U+FF21 is 10) and
    /// `isNumber` accepts Arabic-Indic, Devanagari, circled and superscript digits.
    /// Without an explicit `isASCII` guard the shim would return a number for input
    /// V8 refuses — inventing a tax rate out of a string the engine reads as NaN.
    func testUnicodeDigitLookalikesAreRejectedTheWayJavaScriptRejectsThem() {
        for lookalike in ["0x\u{FF10}", "0x\u{FF21}\u{FF21}", "0b\u{FF11}", "0o\u{FF17}",
                          "\u{FF15}", "\u{0665}", "\u{096B}", "\u{2460}", "\u{00B2}",
                          "1\u{FF10}"] {
            XCTAssertTrue(ReportMath.number(.string(lookalike)).isNaN,
                          "Number(\(lookalike.debugDescription)) is NaN in V8")
        }
        XCTAssertEqual(Character("\u{FF10}").hexDigitValue, 0,
                       "the stdlib behaviour the isASCII guard exists to block")
        XCTAssertTrue(Character("\u{0665}").isNumber,
                      "…and isNumber is Unicode-aware too, which is why the decimal path guards as well")
        // The ASCII forms still work, so the guard did not over-reject.
        XCTAssertEqual(ReportMath.number(.string("0x10")), 16)
        XCTAssertEqual(ReportMath.number(.string("15")), 15)
    }

    /// `us.js:142` and the rounders in jp/eu/kr/tw carry `|| 0`; `cn.js:43` does
    /// NOT. That single difference is why `malformed-US-2025.json` records
    /// `annualIncomeTax: 0` where `malformed-CN-2025.json` records `null`.
    func testOnlyChinasRounderLetsNaNThrough() {
        XCTAssertTrue(ReportMath.round2(.nan).isNaN, "cn.js:43 — no guard, NaN → JSON null")
        XCTAssertEqual(ReportMath.round2OrZero(.nan), 0, "us.js:142 — `|| 0` flattens it")
        XCTAssertEqual(ReportMath.round2OrZero(nil), 0)
        XCTAssertEqual(ReportMath.round2OrZero(12.345), 12.35)
        XCTAssertTrue(ReportMath.percent2(.nan).isNaN, "cn.js:30/41 — margins are unguarded too")
    }
}
