import Foundation

/// The exported artefact: one document as a self-contained HTML file (Q7).
///
/// This is a port of `components/documentPdf.ts`'s `buildDocumentHtml`, and the acceptance line is
/// Q7-b's: for a **non-statement** document with `currency IS NULL` under the **CN** regime, with a
/// fixed `generatedAt` injected, the bytes this returns must equal the bytes that function returns.
/// Six committed goldens — one per language, generated by node from the real module — are what hold
/// that claim; `DocumentExportTests` compares against them.
///
/// ## Why it takes labels instead of looking them up
///
/// Two constraints, and they point the same way:
///
///  * `DC9` requires every `documents.*` key to be named by `DocumentPageComposition` and by no
///    other file. Its second half scans for the namespace as a STRING LITERAL rather than key by
///    key, so an interpolated key cannot slip past — which also means this file may not so much as
///    quote that prefix in a comment. A renderer that resolved its own keys would break the set;
///    one that merely mentioned the prefix would fail the same assertion for no reason at all.
///  * The other app's module says the same thing about itself ("本模块零 i18n/零会计口径依赖"): its
///    labels arrive as `DocumentPdfLabels`. Taking them as parameters is the mirror, not a choice.
///
/// ## Why nothing here touches the filesystem
///
/// `Sources/SoloLedgerCore/Documents/` makes **zero** filesystem calls, and §3's registration of the
/// three concurrency windows (A9–A11) leans on that measurement for its "no reachable harm" arm. A
/// renderer that wrote its own file would retire that argument. This returns a `String`; the save
/// panel in `FilePanels` is what writes it.
public enum DocumentHTML {

    /// Every piece of text the artefact shows that is not a value from the ledger.
    ///
    /// One-for-one with the other app's `DocumentPdfLabels`, plus ``currencyLabel`` — the fourth
    /// extension of Q8's exception, which has no counterpart over there because that app has no
    /// `currency` column to render.
    public struct Labels: Equatable, Sendable {
        /// The `<html lang>` value, and the key `cjkFonts` selects on.
        ///
        /// **B7**: this is the OTHER app's language code (`zh-CN` / `zh-TW`), not this app's
        /// (`zh-Hans` / `zh-Hant`). Emitting this app's code would change both the font fallback
        /// and the artefact's bytes; the mapping happens once, at this boundary.
        public let lang: String
        public let typeTitle: String
        /// Empty for anything that is not void — the other app passes `''` the same way.
        public let voidBadge: String
        public let numberLabel: String
        public let dateLabel: String
        public let validUntilLabel: String
        public let periodLabel: String
        /// Q8's fourth extension. Drawn only when the document carries a `currency`.
        public let currencyLabel: String
        public let customerLabel: String
        public let customerTaxIDLabel: String
        public let customerAddressLabel: String
        public let customerContactLabel: String
        public let descriptionLabel: String
        public let quantityLabel: String
        public let unitPriceLabel: String
        public let taxRateLabel: String
        public let taxAmountLabel: String
        public let amountLabel: String
        public let subtotalLabel: String
        public let totalLabel: String
        public let notesLabel: String
        public let generatedAtLabel: String
        public let disclaimer: String

        public init(lang: String, typeTitle: String, voidBadge: String, numberLabel: String,
                    dateLabel: String, validUntilLabel: String, periodLabel: String,
                    currencyLabel: String, customerLabel: String, customerTaxIDLabel: String,
                    customerAddressLabel: String, customerContactLabel: String,
                    descriptionLabel: String, quantityLabel: String, unitPriceLabel: String,
                    taxRateLabel: String, taxAmountLabel: String, amountLabel: String,
                    subtotalLabel: String, totalLabel: String, notesLabel: String,
                    generatedAtLabel: String, disclaimer: String) {
            self.lang = lang
            self.typeTitle = typeTitle
            self.voidBadge = voidBadge
            self.numberLabel = numberLabel
            self.dateLabel = dateLabel
            self.validUntilLabel = validUntilLabel
            self.periodLabel = periodLabel
            self.currencyLabel = currencyLabel
            self.customerLabel = customerLabel
            self.customerTaxIDLabel = customerTaxIDLabel
            self.customerAddressLabel = customerAddressLabel
            self.customerContactLabel = customerContactLabel
            self.descriptionLabel = descriptionLabel
            self.quantityLabel = quantityLabel
            self.unitPriceLabel = unitPriceLabel
            self.taxRateLabel = taxRateLabel
            self.taxAmountLabel = taxAmountLabel
            self.amountLabel = amountLabel
            self.subtotalLabel = subtotalLabel
            self.totalLabel = totalLabel
            self.notesLabel = notesLabel
            self.generatedAtLabel = generatedAtLabel
            self.disclaimer = disclaimer
        }
    }

    /// The three things the caller computes, exactly as `DocumentPdfOptions` does.
    public struct Options {
        /// `formatMoney` bound to the document's frozen regime — the presentation layer's, so the
        /// rounding stays decided in one place.
        public let money: (Double) -> String
        /// The stored unit's label, or the stored text when this app has no label for it.
        public let unitLabel: (String?) -> String
        /// **B6**: an ISO-8601 UTC instant, not `toLocaleString`. The other app formats this with
        /// the host's ICU, which has no stable format contract to port; a fixed, injectable string
        /// is also what lets Q7-b's byte-for-byte domain exist at all.
        public let generatedAt: String

        public init(money: @escaping (Double) -> String,
                    unitLabel: @escaping (String?) -> String,
                    generatedAt: String) {
            self.money = money
            self.unitLabel = unitLabel
            self.generatedAt = generatedAt
        }
    }

    /// The language code the ARTEFACT carries, from this app's own (**B7**).
    ///
    /// Two codes differ and the rest are shared. Emitting this app's `zh-Hans` would change two
    /// things at once: the `<html lang>` a browser reads, and — because ``cjkFonts(_:)`` keys on
    /// the same string — which CJK family a reader falls back to. The mapping happens here, once,
    /// at the boundary where the file is built, and nowhere else in the app.
    public static func artefactLanguage(for language: String) -> String {
        switch language {
        case "zh-Hans": return "zh-CN"
        case "zh-Hant": return "zh-TW"
        default:        return language
        }
    }

    /// The artefact's file name (Q7-a): `<doc_number>.html`.
    ///
    /// The escape is the other app's, character for character —
    /// `docNumber.replace(/[\\/:*?"<>|\s]+/g, '_')` — so a run of illegal characters or whitespace
    /// folds into ONE underscore rather than one each, and a number that escapes to nothing falls
    /// back to the document's id. Two differences from over there are Q7-a's own and predate this:
    /// no `SoloLedger-` prefix, and `.html` rather than `.pdf`.
    ///
    /// **Uniqueness is not claimed.** `(doc_type, doc_number)` is what the ledger makes unique, so
    /// two documents of different types can share a number and therefore a file name; the save
    /// panel is what surfaces the collision, and Q7-a registers that rather than promising more.
    public static func fileName(for document: BusinessDocument) -> String {
        let illegal = Set("\\/:*?\"<>|")
        var out = ""
        var pendingUnderscore = false
        for character in document.number {
            if illegal.contains(character) || character.isWhitespace {
                pendingUnderscore = true
                continue
            }
            if pendingUnderscore {
                out.append("_")
                pendingUnderscore = false
            }
            out.append(character)
        }
        if pendingUnderscore { out.append("_") }
        return (out.isEmpty ? document.id : out) + ".html"
    }

    /// `escapeHtml` — the same five replacements in the same order, `&` first.
    ///
    /// Order is not cosmetic: replacing `&` after `<` would double-escape the ampersands the other
    /// four introduce. `nil` is the empty string, which is what `String(s ?? '')` does with `null`.
    public static func escape(_ text: String?) -> String {
        guard let text else { return "" }
        return text
            .replacingOccurrences(of: "&", with: "&amp;")
            .replacingOccurrences(of: "<", with: "&lt;")
            .replacingOccurrences(of: ">", with: "&gt;")
            .replacingOccurrences(of: "\"", with: "&quot;")
            .replacingOccurrences(of: "'", with: "&#39;")
    }

    /// The CJK font stack, ordered by language so the regional glyph variants come out right.
    ///
    /// Keyed on the OTHER app's language codes (B7). All system fonts, nothing embedded.
    static func cjkFonts(_ lang: String) -> String {
        if lang == "ja" {
            return "\"Hiragino Sans\",\"Hiragino Kaku Gothic ProN\",\"Yu Gothic\",\"Noto Sans CJK JP\",\"PingFang SC\""
        }
        if lang == "zh-TW" {
            return "\"PingFang TC\",\"Hiragino Sans CNS\",\"Microsoft JhengHei\",\"Noto Sans CJK TC\",\"PingFang SC\""
        }
        if lang == "ko" {
            return "\"Apple SD Gothic Neo\",\"Malgun Gothic\",\"Noto Sans CJK KR\",\"PingFang SC\""
        }
        return "\"PingFang SC\",\"Hiragino Sans\",\"Hiragino Kaku Gothic ProN\",\"Microsoft YaHei\",\"Noto Sans CJK SC\""
    }

    /// Build the artefact.
    ///
    /// - Parameter companyName: **B5** — the letterhead's only field. The other app also prints the
    ///   credit code, address and legal person from its `company_info`; this app's settings hold
    ///   `company_name` and nothing else, so the small-print line never appears. Empty renders as
    ///   the em dash the other app falls back to.
    public static func build(_ detail: BusinessDocumentDetail,
                             companyName: String,
                             labels: Labels,
                             options: Options) -> String {
        let document = detail.document
        let e = escape

        // Number / date / optional valid-until / optional statement period, in that order.
        var meta = "<span>\(e(labels.numberLabel)): \(e(document.number))</span>"
        meta += "<span>\(e(labels.dateLabel)): \(e(document.date))</span>"
        if let validUntil = document.validUntil, !validUntil.isEmpty {
            meta += "<span>\(e(labels.validUntilLabel)): \(e(validUntil))</span>"
        }
        if let start = document.periodStart, !start.isEmpty,
           let end = document.periodEnd, !end.isEmpty {
            meta += "<span>\(e(labels.periodLabel)): \(e(start)) ~ \(e(end))</span>"
        }

        // Q8's fourth extension: its own row, and only when the column holds something. A document
        // whose `currency` is NULL produces no row at all, which is what keeps such documents inside
        // Q7-b's byte-for-byte domain.
        var currencyRow = ""
        if let currency = document.currency, !currency.isEmpty {
            currencyRow = "\n<div class=\"meta\"><span>\(e(labels.currencyLabel)): \(e(currency))</span></div>"
        }

        var customer = "<div class=\"cline\"><span class=\"clabel\">\(e(labels.customerLabel))</span>\(e(document.customerName))</div>"
        if let taxID = document.customerTaxID, !taxID.isEmpty {
            customer += "<div class=\"cline\"><span class=\"clabel\">\(e(labels.customerTaxIDLabel))</span>\(e(taxID))</div>"
        }
        if let address = document.customerAddress, !address.isEmpty {
            customer += "<div class=\"cline\"><span class=\"clabel\">\(e(labels.customerAddressLabel))</span>\(e(address))</div>"
        }
        if let contact = document.customerContact, !contact.isEmpty {
            customer += "<div class=\"cline\"><span class=\"clabel\">\(e(labels.customerContactLabel))</span>\(e(contact))</div>"
        }

        let isStatement = document.type == .statement
        let head = isStatement ? statementHead(labels) : itemHead(labels)
        let rows = detail.items
            .map { isStatement ? statementRow($0, labels: labels, options: options)
                               : itemRow($0, labels: labels, options: options) }
            .joined()

        let voidBadge = labels.voidBadge.isEmpty ? "" : "<span class=\"void\">\(e(labels.voidBadge))</span>"
        var notes = ""
        if let text = document.notes, !text.isEmpty {
            notes = "<div class=\"notes\"><div class=\"nlabel\">\(e(labels.notesLabel))</div>\(e(text))</div>"
        }

        return """
        <!DOCTYPE html><html lang="\(e(labels.lang))"><head><meta charset="utf-8"><style>
        *{box-sizing:border-box;}
        body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",\(cjkFonts(labels.lang)),sans-serif;color:#191918;margin:0;padding:32px;font-size:13px;line-height:1.5;}
        .hdr{border-bottom:2px solid #274C92;padding-bottom:14px;margin-bottom:16px;}
        .company{font-size:20px;font-weight:700;}
        .cmeta{margin-top:4px;font-size:11px;color:#5c5c5a;}
        .cmeta span{margin-right:16px;}
        .rname{font-size:16px;margin-top:12px;font-weight:700;color:#333;}
        .void{margin-left:10px;font-size:11px;font-weight:700;color:#be123c;border:1px solid #be123c;border-radius:4px;padding:1px 6px;vertical-align:middle;}
        .meta{margin-top:6px;font-size:11px;color:#5c5c5a;}
        .meta span{margin-right:20px;}
        .cust{margin:0 0 14px;font-size:12px;}
        .cline{margin-top:2px;}
        .clabel{display:inline-block;min-width:90px;color:#5c5c5a;margin-right:8px;}
        table{width:100%;border-collapse:collapse;margin-top:4px;}
        th{padding:7px 10px;border-bottom:2px solid #e0ddd5;font-size:11px;color:#5c5c5a;text-align:left;font-weight:600;}
        th.val{text-align:right;}
        td{padding:7px 10px;border-bottom:1px solid #eee;}
        td.val{text-align:right;white-space:nowrap;font-variant-numeric:tabular-nums;}
        .totals{margin-top:12px;margin-left:auto;width:60%;font-size:13px;}
        .totals .trow{display:flex;justify-content:space-between;padding:4px 10px;}
        .totals .grand{font-weight:700;font-size:14px;border-top:2px solid #e0ddd5;margin-top:4px;padding-top:8px;}
        .notes{margin-top:18px;font-size:12px;color:#4a4a48;white-space:pre-wrap;}
        .nlabel{font-weight:700;font-size:11px;color:#5c5c5a;margin-bottom:3px;}
        .footer{margin-top:24px;font-size:10px;color:#8a8a88;border-top:1px solid #eee;padding-top:10px;}
        </style></head><body>
        <div class="hdr">
        <div class="company">\(e(companyName.isEmpty ? "—" : companyName))</div>

        <div class="rname">\(e(labels.typeTitle))\(voidBadge)</div>
        <div class="meta">\(meta)</div>\(currencyRow)
        </div>
        <div class="cust">\(customer)</div>
        <table>
        <thead>\(head)</thead>
        <tbody>\(rows)</tbody>
        </table>
        <div class="totals">
        <div class="trow"><span>\(e(labels.subtotalLabel))</span><span>\(e(options.money(DocumentMath.truthyOrZero(document.subtotal))))</span></div>
        <div class="trow"><span>\(e(labels.taxAmountLabel))</span><span>\(e(options.money(DocumentMath.truthyOrZero(document.taxAmount))))</span></div>
        <div class="trow grand"><span>\(e(labels.totalLabel))</span><span>\(e(options.money(DocumentMath.truthyOrZero(document.total))))</span></div>
        </div>
        \(notes)
        <div class="footer">\(e(labels.disclaimer))<br>\(e(labels.generatedAtLabel)): \(e(options.generatedAt))</div>
        </body></html>
        """
    }

    // MARK: - The two line tables

    /// The six columns every type but a statement gets.
    private static func itemHead(_ labels: Labels) -> String {
        "<tr><th>\(escape(labels.descriptionLabel))</th>"
            + "<th class=\"val\">\(escape(labels.quantityLabel))</th>"
            + "<th class=\"val\">\(escape(labels.unitPriceLabel))</th>"
            + "<th class=\"val\">\(escape(labels.taxRateLabel))</th>"
            + "<th class=\"val\">\(escape(labels.taxAmountLabel))</th>"
            + "<th class=\"val\">\(escape(labels.amountLabel))</th></tr>"
    }

    private static func itemRow(_ item: BusinessDocumentItem,
                                labels: Labels, options: Options) -> String {
        // `String(it.quantity)` over there, which is why a stored `0` prints as "0" rather than
        // being folded away — the null check is on the VALUE being absent, not on it being falsy.
        let quantity = item.quantity.map(DocumentMath.jsNumberToString) ?? ""
        let unit = options.unitLabel(item.unit)
        let separator = (!quantity.isEmpty && !unit.isEmpty) ? " " : ""
        let price = item.unitPrice.map(options.money) ?? ""
        return "<tr><td>\(escape(item.description))</td>"
            + "<td class=\"val\">\(escape(quantity + separator + unit))</td>"
            + "<td class=\"val\">\(escape(price))</td>"
            + "<td class=\"val\">\(escape(item.taxRate ?? ""))</td>"
            + "<td class=\"val\">\(escape(options.money(DocumentMath.truthyOrZero(item.taxAmount))))</td>"
            + "<td class=\"val\">\(escape(options.money(DocumentMath.truthyOrZero(item.amount))))</td></tr>"
    }

    /// Q2-b's four columns, in the order the screen already draws them.
    ///
    /// **The date is a column, not a prefix.** The other app has no such column: `salesToRow` glues
    /// the source date onto the front of the description string, so its six-column table shows the
    /// date inside the description cell and leaves quantity, unit price and rate blank. Q2-b took
    /// the date out of the text and gave it a column, which means copying the six-column table here
    /// would lose the date entirely — `ref_date` is the only date a line carries.
    ///
    /// The rate column is absent because Q2-b forbids it outright, not because it would be empty.
    private static func statementHead(_ labels: Labels) -> String {
        "<tr><th>\(escape(labels.descriptionLabel))</th>"
            + "<th>\(escape(labels.dateLabel))</th>"
            + "<th class=\"val\">\(escape(labels.taxAmountLabel))</th>"
            + "<th class=\"val\">\(escape(labels.amountLabel))</th></tr>"
    }

    private static func statementRow(_ item: BusinessDocumentItem,
                                     labels: Labels, options: Options) -> String {
        "<tr><td>\(escape(item.description))</td>"
            + "<td>\(escape(item.refDate ?? ""))</td>"
            + "<td class=\"val\">\(escape(options.money(DocumentMath.truthyOrZero(item.taxAmount))))</td>"
            + "<td class=\"val\">\(escape(options.money(DocumentMath.truthyOrZero(item.amount))))</td></tr>"
    }
}
