// 6 国预置类别种子数据 — 详见 docs/INTERNATIONALIZATION_PLAN.md §4
// id 命名规则：{locale}-{type}-{slug}，slug 与 schedule_line 强映射
// 修改本文件时同步 i18n locale 文件里的类别名称

const SEEDS = [
  // ============================ 🇨🇳 CN ============================
  // Income
  { id: 'cn-income-sales',         locale: 'CN', type: 'income',  slug: 'sales',           label_zh_cn: '主营业务收入', label_zh_tw: '主營業務收入', label_en: 'Sales Revenue',         label_ja: '売上高',     label_ko: '매출',           label_fr: 'Chiffre d\'affaires',  schedule_line: '损益表-营业收入', sort_order: 10 },
  { id: 'cn-income-other',         locale: 'CN', type: 'income',  slug: 'other-revenue',   label_zh_cn: '其他业务收入', label_zh_tw: '其他業務收入', label_en: 'Other Revenue',         label_ja: '営業外収益', label_ko: '기타영업수익',     label_fr: 'Autres produits',       schedule_line: '损益表-其他业务收入', sort_order: 20 },
  { id: 'cn-income-interest',      locale: 'CN', type: 'income',  slug: 'interest',        label_zh_cn: '利息收入',   label_zh_tw: '利息收入',   label_en: 'Interest Income',       label_ja: '受取利息',   label_ko: '이자수익',       label_fr: 'Produits financiers',   schedule_line: '损益表-财务收入', sort_order: 30 },
  // Expense
  { id: 'cn-expense-cogs',         locale: 'CN', type: 'expense', slug: 'cogs',            label_zh_cn: '营业成本',   label_zh_tw: '營業成本',   label_en: 'Cost of Goods Sold',    label_ja: '売上原価',   label_ko: '매출원가',       label_fr: 'Coût des marchandises', schedule_line: '损益表-营业成本', sort_order: 10 },
  { id: 'cn-expense-selling',      locale: 'CN', type: 'expense', slug: 'selling',         label_zh_cn: '销售费用',   label_zh_tw: '銷售費用',   label_en: 'Selling Expense',       label_ja: '販売費',     label_ko: '판매비',         label_fr: 'Frais commerciaux',     schedule_line: '损益表-销售费用', sort_order: 20 },
  { id: 'cn-expense-admin',        locale: 'CN', type: 'expense', slug: 'admin',           label_zh_cn: '管理费用',   label_zh_tw: '管理費用',   label_en: 'Administrative Expense',label_ja: '一般管理費', label_ko: '관리비',         label_fr: 'Frais administratifs',  schedule_line: '损益表-管理费用', sort_order: 30 },
  { id: 'cn-expense-financial',    locale: 'CN', type: 'expense', slug: 'financial',       label_zh_cn: '财务费用',   label_zh_tw: '財務費用',   label_en: 'Financial Expense',     label_ja: '財務費用',   label_ko: '재무비용',       label_fr: 'Frais financiers',      schedule_line: '损益表-财务费用', sort_order: 40 },
  { id: 'cn-expense-tax-surcharge',locale: 'CN', type: 'expense', slug: 'tax-surcharge',   label_zh_cn: '营业税金及附加',label_zh_tw: '營業稅金及附加', label_en: 'Tax Surcharge',     label_ja: '租税公課',   label_ko: '제세공과금',     label_fr: 'Taxes & impôts',        schedule_line: '损益表-税金及附加', sort_order: 50 },
  { id: 'cn-expense-income-tax',   locale: 'CN', type: 'expense', slug: 'income-tax',      label_zh_cn: '所得税',     label_zh_tw: '所得稅',     label_en: 'Income Tax',            label_ja: '法人税',     label_ko: '법인세',         label_fr: 'Impôt sur le revenu',   schedule_line: '损益表-所得税', sort_order: 60 },

  // ============================ 🇺🇸 US (Schedule C) ============================
  // Income
  { id: 'us-income-gross-receipts',locale: 'US', type: 'income',  slug: 'gross-receipts',  label_zh_cn: '总收入或销售额',  label_zh_tw: '總收入或銷售額',  label_en: 'Gross Receipts',        label_ja: '総収入',     label_ko: '총수입',         label_fr: 'Recettes brutes',       schedule_line: 'Schedule C Line 1',  sort_order: 10 },
  { id: 'us-income-returns',       locale: 'US', type: 'income',  slug: 'returns',         label_zh_cn: '退货与折让',  label_zh_tw: '退貨與折讓',  label_en: 'Returns & Allowances',  label_ja: '返品・値引',  label_ko: '반품·할인',       label_fr: 'Retours & rabais',      schedule_line: 'Schedule C Line 2',  sort_order: 20 },
  { id: 'us-income-other',         locale: 'US', type: 'income',  slug: 'other-income',    label_zh_cn: '其他收入',    label_zh_tw: '其他收入',    label_en: 'Other Income',          label_ja: 'その他収入',  label_ko: '기타수입',       label_fr: 'Autres revenus',        schedule_line: 'Schedule C Line 6',  sort_order: 30 },
  // Expense (Part II Lines 8-27)
  { id: 'us-expense-advertising',  locale: 'US', type: 'expense', slug: 'advertising',     label_zh_cn: '广告费',     label_zh_tw: '廣告費',     label_en: 'Advertising',           label_ja: '広告宣伝費', label_ko: '광고선전비',     label_fr: 'Publicité',             schedule_line: 'Schedule C Line 8',  sort_order: 10 },
  { id: 'us-expense-car',          locale: 'US', type: 'expense', slug: 'car-truck',       label_zh_cn: '车辆费用',   label_zh_tw: '車輛費用',   label_en: 'Car & Truck Expenses',  label_ja: '車両費',     label_ko: '차량유지비',     label_fr: 'Frais de véhicule',     schedule_line: 'Schedule C Line 9',  sort_order: 20 },
  { id: 'us-expense-commissions',  locale: 'US', type: 'expense', slug: 'commissions',     label_zh_cn: '佣金',       label_zh_tw: '佣金',       label_en: 'Commissions & Fees',    label_ja: '手数料',     label_ko: '수수료',         label_fr: 'Commissions',           schedule_line: 'Schedule C Line 10', sort_order: 30 },
  { id: 'us-expense-contract',     locale: 'US', type: 'expense', slug: 'contract-labor',  label_zh_cn: '外包劳务',   label_zh_tw: '外包勞務',   label_en: 'Contract Labor',        label_ja: '外注費',     label_ko: '외주용역비',     label_fr: 'Sous-traitance',        schedule_line: 'Schedule C Line 11', sort_order: 40 },
  { id: 'us-expense-depreciation', locale: 'US', type: 'expense', slug: 'depreciation',    label_zh_cn: '折旧',       label_zh_tw: '折舊',       label_en: 'Depreciation',          label_ja: '減価償却',   label_ko: '감가상각비',     label_fr: 'Amortissements',        schedule_line: 'Schedule C Line 13', sort_order: 50 },
  { id: 'us-expense-insurance',    locale: 'US', type: 'expense', slug: 'insurance',       label_zh_cn: '保险（非健康）',label_zh_tw: '保險（非健康）',label_en: 'Insurance (non-health)',label_ja: '保険料',     label_ko: '보험료',         label_fr: 'Assurance',             schedule_line: 'Schedule C Line 15', sort_order: 60 },
  { id: 'us-expense-interest',     locale: 'US', type: 'expense', slug: 'interest',        label_zh_cn: '利息支出',   label_zh_tw: '利息支出',   label_en: 'Interest',              label_ja: '支払利息',   label_ko: '이자비용',       label_fr: 'Intérêts',              schedule_line: 'Schedule C Line 16b', sort_order: 70 },
  { id: 'us-expense-legal',        locale: 'US', type: 'expense', slug: 'legal-pro',       label_zh_cn: '法律与专业服务', label_zh_tw: '法律與專業服務', label_en: 'Legal & Professional', label_ja: '専門家報酬', label_ko: '법무·전문가비',  label_fr: 'Honoraires',            schedule_line: 'Schedule C Line 17', sort_order: 80 },
  { id: 'us-expense-office',       locale: 'US', type: 'expense', slug: 'office',          label_zh_cn: '办公费用',   label_zh_tw: '辦公費用',   label_en: 'Office Expense',        label_ja: '事務用品費', label_ko: '사무용품비',     label_fr: 'Fournitures bureau',    schedule_line: 'Schedule C Line 18', sort_order: 90 },
  { id: 'us-expense-rent',         locale: 'US', type: 'expense', slug: 'rent',            label_zh_cn: '租金',       label_zh_tw: '租金',       label_en: 'Rent',                  label_ja: '地代家賃',   label_ko: '임차료',         label_fr: 'Loyer',                 schedule_line: 'Schedule C Line 20', sort_order: 100 },
  { id: 'us-expense-repairs',      locale: 'US', type: 'expense', slug: 'repairs',         label_zh_cn: '维修费',     label_zh_tw: '維修費',     label_en: 'Repairs & Maintenance', label_ja: '修繕費',     label_ko: '수선유지비',     label_fr: 'Réparations',           schedule_line: 'Schedule C Line 21', sort_order: 110 },
  { id: 'us-expense-supplies',     locale: 'US', type: 'expense', slug: 'supplies',        label_zh_cn: '耗材',       label_zh_tw: '耗材',       label_en: 'Supplies',              label_ja: '消耗品費',   label_ko: '소모품비',       label_fr: 'Fournitures',           schedule_line: 'Schedule C Line 22', sort_order: 120 },
  { id: 'us-expense-taxes',        locale: 'US', type: 'expense', slug: 'taxes',           label_zh_cn: '税款与执照',  label_zh_tw: '稅款與執照',  label_en: 'Taxes & Licenses',      label_ja: '租税公課',   label_ko: '제세공과금',     label_fr: 'Taxes & licences',      schedule_line: 'Schedule C Line 23', sort_order: 130 },
  { id: 'us-expense-travel',       locale: 'US', type: 'expense', slug: 'travel',          label_zh_cn: '差旅',       label_zh_tw: '差旅',       label_en: 'Travel',                label_ja: '旅費交通費', label_ko: '여비교통비',     label_fr: 'Frais de déplacement',  schedule_line: 'Schedule C Line 24a', sort_order: 140 },
  { id: 'us-expense-meals',        locale: 'US', type: 'expense', slug: 'meals',           label_zh_cn: '餐费（50%可抵）',label_zh_tw: '餐費（50%可抵）',label_en: 'Meals (50%)',        label_ja: '接待交際費（50%）',label_ko: '식비(50%)',      label_fr: 'Repas (50%)',           schedule_line: 'Schedule C Line 24b', deductible_pct: 50, sort_order: 150 },
  { id: 'us-expense-utilities',    locale: 'US', type: 'expense', slug: 'utilities',       label_zh_cn: '水电网',     label_zh_tw: '水電網',     label_en: 'Utilities',             label_ja: '水道光熱費', label_ko: '수도광열비',     label_fr: 'Énergie',               schedule_line: 'Schedule C Line 25', sort_order: 160 },
  { id: 'us-expense-wages',        locale: 'US', type: 'expense', slug: 'wages',           label_zh_cn: '工资',       label_zh_tw: '工資',       label_en: 'Wages',                 label_ja: '給料手当',   label_ko: '급여',           label_fr: 'Salaires',              schedule_line: 'Schedule C Line 26', sort_order: 170 },
  { id: 'us-expense-other',        locale: 'US', type: 'expense', slug: 'other',           label_zh_cn: '其他费用',   label_zh_tw: '其他費用',   label_en: 'Other Expenses',        label_ja: '雑費',       label_ko: '잡비',           label_fr: 'Autres charges',        schedule_line: 'Schedule C Line 27a', sort_order: 180 },
  { id: 'us-expense-home-office',  locale: 'US', type: 'expense', slug: 'home-office',     label_zh_cn: '家庭办公室', label_zh_tw: '家庭辦公室', label_en: 'Home Office',           label_ja: '在宅オフィス', label_ko: '재택사무실',     label_fr: 'Bureau à domicile',     schedule_line: 'Form 8829', sort_order: 190 },

  // ============================ 🇯🇵 JP ============================
  // Income
  { id: 'jp-income-sales',         locale: 'JP', type: 'income',  slug: 'sales',           label_zh_cn: '销售额',     label_zh_tw: '銷售額',     label_en: 'Sales',                 label_ja: '売上高',     label_ko: '매출',           label_fr: 'Ventes',                schedule_line: '損益計算書-売上高', sort_order: 10 },
  { id: 'jp-income-other',         locale: 'JP', type: 'income',  slug: 'other',           label_zh_cn: '营业外收益', label_zh_tw: '營業外收益', label_en: 'Non-Operating Income',  label_ja: '営業外収益', label_ko: '영업외수익',     label_fr: 'Produits hors exploitation', schedule_line: '損益計算書-営業外収益', sort_order: 20 },
  // Expense
  { id: 'jp-expense-cogs',         locale: 'JP', type: 'expense', slug: 'cogs',            label_zh_cn: '销货成本',   label_zh_tw: '銷貨成本',   label_en: 'Cost of Goods Sold',    label_ja: '売上原価',   label_ko: '매출원가',       label_fr: 'Coût des ventes',       schedule_line: '損益計算書-売上原価', sort_order: 10 },
  { id: 'jp-expense-salary',       locale: 'JP', type: 'expense', slug: 'salary',          label_zh_cn: '工资',       label_zh_tw: '工資',       label_en: 'Salaries',              label_ja: '給料手当',   label_ko: '급여',           label_fr: 'Salaires',              schedule_line: '販管費-給料手当', sort_order: 20 },
  { id: 'jp-expense-travel',       locale: 'JP', type: 'expense', slug: 'travel',          label_zh_cn: '差旅交通',   label_zh_tw: '差旅交通',   label_en: 'Travel',                label_ja: '旅費交通費', label_ko: '여비교통비',     label_fr: 'Déplacements',          schedule_line: '販管費-旅費交通費', sort_order: 30 },
  { id: 'jp-expense-comm',         locale: 'JP', type: 'expense', slug: 'communication',   label_zh_cn: '通讯',       label_zh_tw: '通訊',       label_en: 'Communication',         label_ja: '通信費',     label_ko: '통신비',         label_fr: 'Télécom',               schedule_line: '販管費-通信費', sort_order: 40 },
  { id: 'jp-expense-utilities',    locale: 'JP', type: 'expense', slug: 'utilities',       label_zh_cn: '水电费',     label_zh_tw: '水電費',     label_en: 'Utilities',             label_ja: '水道光熱費', label_ko: '수도광열비',     label_fr: 'Énergie',               schedule_line: '販管費-水道光熱費', sort_order: 50 },
  { id: 'jp-expense-supplies',     locale: 'JP', type: 'expense', slug: 'supplies',        label_zh_cn: '消耗品',     label_zh_tw: '消耗品',     label_en: 'Supplies',              label_ja: '消耗品費',   label_ko: '소모품비',       label_fr: 'Fournitures',           schedule_line: '販管費-消耗品費', sort_order: 60 },
  { id: 'jp-expense-entertain',    locale: 'JP', type: 'expense', slug: 'entertain',       label_zh_cn: '招待交际',   label_zh_tw: '招待交際',   label_en: 'Entertainment',         label_ja: '接待交際費', label_ko: '접대비',         label_fr: 'Représentation',        schedule_line: '販管費-接待交際費', sort_order: 70 },
  { id: 'jp-expense-ad',           locale: 'JP', type: 'expense', slug: 'advertising',     label_zh_cn: '广告',       label_zh_tw: '廣告',       label_en: 'Advertising',           label_ja: '広告宣伝費', label_ko: '광고선전비',     label_fr: 'Publicité',             schedule_line: '販管費-広告宣伝費', sort_order: 80 },
  { id: 'jp-expense-rent',         locale: 'JP', type: 'expense', slug: 'rent',            label_zh_cn: '租金',       label_zh_tw: '租金',       label_en: 'Rent',                  label_ja: '地代家賃',   label_ko: '임차료',         label_fr: 'Loyer',                 schedule_line: '販管費-地代家賃', sort_order: 90 },
  { id: 'jp-expense-tax',          locale: 'JP', type: 'expense', slug: 'tax',             label_zh_cn: '税金',       label_zh_tw: '稅金',       label_en: 'Taxes',                 label_ja: '租税公課',   label_ko: '제세공과금',     label_fr: 'Impôts',                schedule_line: '販管費-租税公課', sort_order: 100 },
  { id: 'jp-expense-dep',          locale: 'JP', type: 'expense', slug: 'depreciation',    label_zh_cn: '折旧',       label_zh_tw: '折舊',       label_en: 'Depreciation',          label_ja: '減価償却費', label_ko: '감가상각비',     label_fr: 'Amortissements',        schedule_line: '販管費-減価償却費', sort_order: 110 },
  { id: 'jp-expense-misc',         locale: 'JP', type: 'expense', slug: 'misc',            label_zh_cn: '杂费',       label_zh_tw: '雜費',       label_en: 'Miscellaneous',         label_ja: '雑費',       label_ko: '잡비',           label_fr: 'Divers',                schedule_line: '販管費-雑費', sort_order: 120 },

  // ============================ 🇪🇺 EU (Generic) ============================
  // Income
  { id: 'eu-income-revenue',       locale: 'EU', type: 'income',  slug: 'revenue',         label_zh_cn: '营业收入',   label_zh_tw: '營業收入',   label_en: 'Revenue',               label_ja: '売上',       label_ko: '매출',           label_fr: 'Chiffre d\'affaires',  schedule_line: 'P&L - Revenue', sort_order: 10 },
  { id: 'eu-income-financial',     locale: 'EU', type: 'income',  slug: 'financial',       label_zh_cn: '财务收入',   label_zh_tw: '財務收入',   label_en: 'Financial Income',      label_ja: '財務収益',   label_ko: '재무수익',       label_fr: 'Produits financiers',  schedule_line: 'P&L - Financial Income', sort_order: 20 },
  // Expense
  { id: 'eu-expense-purchases',    locale: 'EU', type: 'expense', slug: 'purchases',       label_zh_cn: '采购',       label_zh_tw: '採購',       label_en: 'Purchases',             label_ja: '仕入',       label_ko: '매입',           label_fr: 'Achats',                schedule_line: 'P&L - Purchases', sort_order: 10 },
  { id: 'eu-expense-rent',         locale: 'EU', type: 'expense', slug: 'rent',            label_zh_cn: '租金',       label_zh_tw: '租金',       label_en: 'Rent',                  label_ja: '賃料',       label_ko: '임차료',         label_fr: 'Loyer',                 schedule_line: 'P&L - Rent', sort_order: 20 },
  { id: 'eu-expense-salaries',     locale: 'EU', type: 'expense', slug: 'salaries',        label_zh_cn: '工资',       label_zh_tw: '工資',       label_en: 'Salaries',              label_ja: '給与',       label_ko: '급여',           label_fr: 'Salaires',              schedule_line: 'P&L - Salaries', sort_order: 30 },
  { id: 'eu-expense-social',       locale: 'EU', type: 'expense', slug: 'social-charges',  label_zh_cn: '社会保险',   label_zh_tw: '社會保險',   label_en: 'Social Charges',        label_ja: '社会保険料', label_ko: '사회보험료',     label_fr: 'Charges sociales',     schedule_line: 'P&L - Social', sort_order: 40 },
  { id: 'eu-expense-travel',       locale: 'EU', type: 'expense', slug: 'travel',          label_zh_cn: '差旅',       label_zh_tw: '差旅',       label_en: 'Travel',                label_ja: '出張費',     label_ko: '여비교통비',     label_fr: 'Déplacements',          schedule_line: 'P&L - Travel', sort_order: 50 },
  { id: 'eu-expense-fees',         locale: 'EU', type: 'expense', slug: 'professional',    label_zh_cn: '专业服务',   label_zh_tw: '專業服務',   label_en: 'Professional Fees',     label_ja: '専門家報酬', label_ko: '전문가비',       label_fr: 'Honoraires',            schedule_line: 'P&L - Fees', sort_order: 60 },
  { id: 'eu-expense-marketing',    locale: 'EU', type: 'expense', slug: 'marketing',       label_zh_cn: '市场推广',   label_zh_tw: '市場推廣',   label_en: 'Marketing',             label_ja: 'マーケティング', label_ko: '마케팅비',       label_fr: 'Marketing',             schedule_line: 'P&L - Marketing', sort_order: 70 },
  { id: 'eu-expense-energy',       locale: 'EU', type: 'expense', slug: 'energy',          label_zh_cn: '能源',       label_zh_tw: '能源',       label_en: 'Energy',                label_ja: '光熱費',     label_ko: '에너지비',       label_fr: 'Énergie',               schedule_line: 'P&L - Energy', sort_order: 80 },
  { id: 'eu-expense-amortization', locale: 'EU', type: 'expense', slug: 'amortization',    label_zh_cn: '摊销',       label_zh_tw: '攤銷',       label_en: 'Amortization',          label_ja: '償却',       label_ko: '상각비',         label_fr: 'Amortissements',        schedule_line: 'P&L - Amortization', sort_order: 90 },
  { id: 'eu-expense-vat-net',      locale: 'EU', type: 'expense', slug: 'vat-net',         label_zh_cn: 'VAT 应纳',   label_zh_tw: 'VAT 應納',   label_en: 'VAT Payable (Net)',     label_ja: 'VAT 納付',   label_ko: 'VAT 납부',       label_fr: 'TVA à payer',           schedule_line: 'VAT Return', sort_order: 100 },

  // ============================ 🇰🇷 KR ============================
  // Income
  { id: 'kr-income-sales',         locale: 'KR', type: 'income',  slug: 'sales',           label_zh_cn: '销售',       label_zh_tw: '銷售',       label_en: 'Sales',                 label_ja: '売上',       label_ko: '매출',           label_fr: 'Ventes',                schedule_line: '손익계산서-매출', sort_order: 10 },
  { id: 'kr-income-non-op',        locale: 'KR', type: 'income',  slug: 'non-operating',   label_zh_cn: '营业外收益', label_zh_tw: '營業外收益', label_en: 'Non-Operating Income',  label_ja: '営業外収益', label_ko: '영업외수익',     label_fr: 'Produits hors exploitation', schedule_line: '손익계산서-영업외수익', sort_order: 20 },
  // Expense
  { id: 'kr-expense-cogs',         locale: 'KR', type: 'expense', slug: 'cogs',            label_zh_cn: '销售成本',   label_zh_tw: '銷售成本',   label_en: 'Cost of Sales',         label_ja: '売上原価',   label_ko: '매출원가',       label_fr: 'Coût des ventes',       schedule_line: '손익계산서-매출원가', sort_order: 10 },
  { id: 'kr-expense-salary',       locale: 'KR', type: 'expense', slug: 'salary',          label_zh_cn: '工资',       label_zh_tw: '工資',       label_en: 'Salary',                label_ja: '給与',       label_ko: '급여',           label_fr: 'Salaires',              schedule_line: '판관비-급여', sort_order: 20 },
  { id: 'kr-expense-welfare',      locale: 'KR', type: 'expense', slug: 'welfare',         label_zh_cn: '福利',       label_zh_tw: '福利',       label_en: 'Welfare',               label_ja: '福利厚生費', label_ko: '복리후생비',     label_fr: 'Avantages sociaux',     schedule_line: '판관비-복리후생비', sort_order: 30 },
  { id: 'kr-expense-travel',       locale: 'KR', type: 'expense', slug: 'travel',          label_zh_cn: '差旅',       label_zh_tw: '差旅',       label_en: 'Travel',                label_ja: '旅費交通費', label_ko: '여비교통비',     label_fr: 'Déplacements',          schedule_line: '판관비-여비교통비', sort_order: 40 },
  { id: 'kr-expense-comm',         locale: 'KR', type: 'expense', slug: 'communication',   label_zh_cn: '通讯',       label_zh_tw: '通訊',       label_en: 'Communication',         label_ja: '通信費',     label_ko: '통신비',         label_fr: 'Télécom',               schedule_line: '판관비-통신비', sort_order: 50 },
  { id: 'kr-expense-utilities',    locale: 'KR', type: 'expense', slug: 'utilities',       label_zh_cn: '水电费',     label_zh_tw: '水電費',     label_en: 'Utilities',             label_ja: '水道光熱費', label_ko: '수도광열비',     label_fr: 'Énergie',               schedule_line: '판관비-수도광열비', sort_order: 60 },
  { id: 'kr-expense-supplies',     locale: 'KR', type: 'expense', slug: 'supplies',        label_zh_cn: '消耗品',     label_zh_tw: '消耗品',     label_en: 'Supplies',              label_ja: '消耗品費',   label_ko: '소모품비',       label_fr: 'Fournitures',           schedule_line: '판관비-소모품비', sort_order: 70 },
  { id: 'kr-expense-entertain',    locale: 'KR', type: 'expense', slug: 'entertain',       label_zh_cn: '招待',       label_zh_tw: '招待',       label_en: 'Entertainment',         label_ja: '接待費',     label_ko: '접대비',         label_fr: 'Représentation',        schedule_line: '판관비-접대비', sort_order: 80 },
  { id: 'kr-expense-ad',           locale: 'KR', type: 'expense', slug: 'advertising',     label_zh_cn: '广告',       label_zh_tw: '廣告',       label_en: 'Advertising',           label_ja: '広告宣伝費', label_ko: '광고선전비',     label_fr: 'Publicité',             schedule_line: '판관비-광고선전비', sort_order: 90 },
  { id: 'kr-expense-rent',         locale: 'KR', type: 'expense', slug: 'rent',            label_zh_cn: '租金',       label_zh_tw: '租金',       label_en: 'Rent',                  label_ja: '賃料',       label_ko: '임차료',         label_fr: 'Loyer',                 schedule_line: '판관비-임차료', sort_order: 100 },
  { id: 'kr-expense-dep',          locale: 'KR', type: 'expense', slug: 'depreciation',    label_zh_cn: '折旧',       label_zh_tw: '折舊',       label_en: 'Depreciation',          label_ja: '減価償却費', label_ko: '감가상각비',     label_fr: 'Amortissements',        schedule_line: '판관비-감가상각비', sort_order: 110 },

  // ============================ 🇹🇼 TW ============================
  // Income
  { id: 'tw-income-sales',         locale: 'TW', type: 'income',  slug: 'sales',           label_zh_cn: '销售收入',   label_zh_tw: '銷售收入',   label_en: 'Sales Revenue',         label_ja: '売上',       label_ko: '매출',           label_fr: 'Ventes',                schedule_line: '損益表-營業收入', sort_order: 10 },
  { id: 'tw-income-other',         locale: 'TW', type: 'income',  slug: 'other',           label_zh_cn: '其他营业收入', label_zh_tw: '其他營業收入', label_en: 'Other Operating Income', label_ja: 'その他営業収益', label_ko: '기타영업수익',   label_fr: 'Autres produits',     schedule_line: '損益表-其他營業收入', sort_order: 20 },
  // Expense
  { id: 'tw-expense-cogs',         locale: 'TW', type: 'expense', slug: 'cogs',            label_zh_cn: '销货成本',   label_zh_tw: '銷貨成本',   label_en: 'Cost of Goods Sold',    label_ja: '売上原価',   label_ko: '매출원가',       label_fr: 'Coût des marchandises', schedule_line: '損益表-銷貨成本', sort_order: 10 },
  { id: 'tw-expense-selling',      locale: 'TW', type: 'expense', slug: 'selling',         label_zh_cn: '推销费用',   label_zh_tw: '推銷費用',   label_en: 'Selling Expense',       label_ja: '販売費',     label_ko: '판매비',         label_fr: 'Frais de vente',        schedule_line: '損益表-推銷費用', sort_order: 20 },
  { id: 'tw-expense-admin',        locale: 'TW', type: 'expense', slug: 'admin',           label_zh_cn: '管理费用',   label_zh_tw: '管理費用',   label_en: 'Administrative Expense',label_ja: '一般管理費', label_ko: '관리비',         label_fr: 'Frais admin',           schedule_line: '損益表-管理費用', sort_order: 30 },
  { id: 'tw-expense-rd',           locale: 'TW', type: 'expense', slug: 'rd',              label_zh_cn: '研发费用',   label_zh_tw: '研發費用',   label_en: 'R&D Expense',           label_ja: '研究開発費', label_ko: '연구개발비',     label_fr: 'R&D',                   schedule_line: '損益表-研究發展費用', sort_order: 40 },
  { id: 'tw-expense-business-tax', locale: 'TW', type: 'expense', slug: 'business-tax',    label_zh_cn: '营业税',     label_zh_tw: '營業稅',     label_en: 'Business Tax',          label_ja: '営業税',     label_ko: '영업세',         label_fr: 'Taxe activité',         schedule_line: '損益表-營業稅', sort_order: 50 },
  { id: 'tw-expense-income-tax',   locale: 'TW', type: 'expense', slug: 'income-tax',      label_zh_cn: '所得税',     label_zh_tw: '所得稅',     label_en: 'Income Tax',            label_ja: '法人税',     label_ko: '법인세',         label_fr: 'Impôt sur le revenu',   schedule_line: '損益表-所得稅', sort_order: 60 },
];

module.exports = { SEEDS };
